name: Build and Publish
on:
    push
        # tags:
        #     - v*

###

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        outputs:
            server_version: ${{ steps.meta.outputs.tags }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to registry
              uses: docker/login-action@v3
              with:
                  registry: ccr.ccs.tencentyun.com
                  username: ${{ secrets.DOCKER_USER_NAME }}
                  password: ${{ secrets.DOCKER_PASSWD }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ccr.ccs.tencentyun.com/${{ github.repository }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

    # deploy_test:
    #     runs-on: ubuntu-latest
    #     needs: build
    #     steps:
    #         - name: Deploy
    #           uses: appleboy/ssh-action@v1
    #           with:
    #               host: ${{ secrets.TEST_SSH_HOST }}
    #               username: ${{ secrets.TEST_SSH_USER }}
    #               key: ${{ secrets.TEST_SSH_KEY }}
    #               port: ${{ secrets.TEST_SSH_PORT }}
    #               script: |
    #                   sed -i "s/SERVER_VERSION=.*/SERVER_VERSION=${{ needs.build.outputs.bot_version }}/" /home/${{ secrets.TEST_SSH_USER }}/.env
    #                   docker-compose -f /home/${{ secrets.TEST_SSH_USER }}/docker-compose.yml up -d
